// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 心跳体
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

// 登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 登录响应
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0=成功, 其它=失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`    // 成功时返回玩家ID
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"` // 成功时返回JWT TOKEN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoginResponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` //0=成功，1=token无效, 2=token过期
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *AuthResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AuthResponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AuthResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

// 聊天消息
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ChatMessage) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` //目标房间ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_proto_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{6}
}

func (x *JoinRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` //0=成功
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	RoomId        int64                  `protobuf:"varint,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` //实际加入的房间ID
	Online        int32                  `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`               //房间内当前人数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_proto_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{7}
}

func (x *JoinRoomResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JoinRoomResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *JoinRoomResponse) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *JoinRoomResponse) GetOnline() int32 {
	if x != nil {
		return x.Online
	}
	return 0
}

type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_proto_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{8}
}

type LeaveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_proto_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{9}
}

func (x *LeaveRoomResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LeaveRoomResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SystemNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"` //通知内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemNotify) Reset() {
	*x = SystemNotify{}
	mi := &file_proto_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemNotify) ProtoMessage() {}

func (x *SystemNotify) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemNotify.ProtoReflect.Descriptor instead.
func (*SystemNotify) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{10}
}

func (x *SystemNotify) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 匹配请求
type MatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	mi := &file_proto_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{13}
}

// 匹配响应（进入匹配队列）
type MatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0=已进入匹配队列
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	mi := &file_proto_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{14}
}

func (x *MatchResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MatchResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 取消匹配
type MatchCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCancelRequest) Reset() {
	*x = MatchCancelRequest{}
	mi := &file_proto_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCancelRequest) ProtoMessage() {}

func (x *MatchCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCancelRequest.ProtoReflect.Descriptor instead.
func (*MatchCancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{15}
}

type MatchCancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0=已取消
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCancelResponse) Reset() {
	*x = MatchCancelResponse{}
	mi := &file_proto_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCancelResponse) ProtoMessage() {}

func (x *MatchCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCancelResponse.ProtoReflect.Descriptor instead.
func (*MatchCancelResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{16}
}

func (x *MatchCancelResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MatchCancelResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 创建房间
type BattleCreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleCreateRoomRequest) Reset() {
	*x = BattleCreateRoomRequest{}
	mi := &file_proto_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleCreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleCreateRoomRequest) ProtoMessage() {}

func (x *BattleCreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleCreateRoomRequest.ProtoReflect.Descriptor instead.
func (*BattleCreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{17}
}

type BattleCreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0=成功
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	RoomCode      string                 `protobuf:"bytes,3,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleCreateRoomResponse) Reset() {
	*x = BattleCreateRoomResponse{}
	mi := &file_proto_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleCreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleCreateRoomResponse) ProtoMessage() {}

func (x *BattleCreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleCreateRoomResponse.ProtoReflect.Descriptor instead.
func (*BattleCreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{18}
}

func (x *BattleCreateRoomResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BattleCreateRoomResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BattleCreateRoomResponse) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

// 加入房间
type BattleJoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCode      string                 `protobuf:"bytes,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleJoinRoomRequest) Reset() {
	*x = BattleJoinRoomRequest{}
	mi := &file_proto_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleJoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleJoinRoomRequest) ProtoMessage() {}

func (x *BattleJoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleJoinRoomRequest.ProtoReflect.Descriptor instead.
func (*BattleJoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{19}
}

func (x *BattleJoinRoomRequest) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

type BattleJoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0=成功, 1=房间不存在
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleJoinRoomResponse) Reset() {
	*x = BattleJoinRoomResponse{}
	mi := &file_proto_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleJoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleJoinRoomResponse) ProtoMessage() {}

func (x *BattleJoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleJoinRoomResponse.ProtoReflect.Descriptor instead.
func (*BattleJoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{20}
}

func (x *BattleJoinRoomResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BattleJoinRoomResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 对局开始（服务端推送）
type BattleStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"` // 对局ID
	Opponent      int64                  `protobuf:"varint,2,opt,name=opponent,proto3" json:"opponent,omitempty"`                 // 对手UID
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`                  // 对手昵称
	Round         int32                  `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`                       // 当前小局（1~7）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleStart) Reset() {
	*x = BattleStart{}
	mi := &file_proto_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleStart) ProtoMessage() {}

func (x *BattleStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleStart.ProtoReflect.Descriptor instead.
func (*BattleStart) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{21}
}

func (x *BattleStart) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *BattleStart) GetOpponent() int64 {
	if x != nil {
		return x.Opponent
	}
	return 0
}

func (x *BattleStart) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *BattleStart) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

// 对局状态（重连时推送）
type BattleState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Opponent      int64                  `protobuf:"varint,2,opt,name=opponent,proto3" json:"opponent,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Round         int32                  `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`                       // 当前小局
	SubRound      int32                  `protobuf:"varint,5,opt,name=sub_round,json=subRound,proto3" json:"sub_round,omitempty"` // 小局内第几张
	Score1        int32                  `protobuf:"varint,6,opt,name=score1,proto3" json:"score1,omitempty"`                     // 玩家1大分
	Score2        int32                  `protobuf:"varint,7,opt,name=score2,proto3" json:"score2,omitempty"`                     // 玩家2大分
	Hand          []int32                `protobuf:"varint,8,rep,packed,name=hand,proto3" json:"hand,omitempty"`                  // 当前手牌列表
	MyTurn        bool                   `protobuf:"varint,9,opt,name=my_turn,json=myTurn,proto3" json:"my_turn,omitempty"`       // 是否轮到我出牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleState) Reset() {
	*x = BattleState{}
	mi := &file_proto_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleState) ProtoMessage() {}

func (x *BattleState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleState.ProtoReflect.Descriptor instead.
func (*BattleState) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{22}
}

func (x *BattleState) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *BattleState) GetOpponent() int64 {
	if x != nil {
		return x.Opponent
	}
	return 0
}

func (x *BattleState) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *BattleState) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *BattleState) GetSubRound() int32 {
	if x != nil {
		return x.SubRound
	}
	return 0
}

func (x *BattleState) GetScore1() int32 {
	if x != nil {
		return x.Score1
	}
	return 0
}

func (x *BattleState) GetScore2() int32 {
	if x != nil {
		return x.Score2
	}
	return 0
}

func (x *BattleState) GetHand() []int32 {
	if x != nil {
		return x.Hand
	}
	return nil
}

func (x *BattleState) GetMyTurn() bool {
	if x != nil {
		return x.MyTurn
	}
	return false
}

// 出牌请求
type PlayCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	CardType      int32                  `protobuf:"varint,2,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"` // 0=平民, 1=国王, 2=奴隶
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayCardRequest) Reset() {
	*x = PlayCardRequest{}
	mi := &file_proto_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayCardRequest) ProtoMessage() {}

func (x *PlayCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayCardRequest.ProtoReflect.Descriptor instead.
func (*PlayCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{23}
}

func (x *PlayCardRequest) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *PlayCardRequest) GetCardType() int32 {
	if x != nil {
		return x.CardType
	}
	return 0
}

// 出牌响应
type PlayCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0=成功, 1=对局已结束, 2=不是你的回合, 3=没有这张牌
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayCardResponse) Reset() {
	*x = PlayCardResponse{}
	mi := &file_proto_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayCardResponse) ProtoMessage() {}

func (x *PlayCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayCardResponse.ProtoReflect.Descriptor instead.
func (*PlayCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{24}
}

func (x *PlayCardResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PlayCardResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 回合结果（服务端推送给双方）
type RoundResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`    // 对局ID
	Round         int32                  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`                          // 第几个小局（1~7）
	SubRound      int32                  `protobuf:"varint,3,opt,name=sub_round,json=subRound,proto3" json:"sub_round,omitempty"`    // 小局内第几张（1~5）
	MyCard        int32                  `protobuf:"varint,4,opt,name=my_card,json=myCard,proto3" json:"my_card,omitempty"`          // 我出的牌
	OpCard        int32                  `protobuf:"varint,5,opt,name=op_card,json=opCard,proto3" json:"op_card,omitempty"`          // 对手出的牌
	Result        int32                  `protobuf:"varint,6,opt,name=result,proto3" json:"result,omitempty"`                        // 本回合: 1=胜, 0=平, -1=负
	Score1        int32                  `protobuf:"varint,7,opt,name=score1,proto3" json:"score1,omitempty"`                        // 玩家1大分
	Score2        int32                  `protobuf:"varint,8,opt,name=score2,proto3" json:"score2,omitempty"`                        // 玩家2大分
	RoundOver     bool                   `protobuf:"varint,9,opt,name=round_over,json=roundOver,proto3" json:"round_over,omitempty"` // 小局是否结束（有人拿分或5张出完）
	GameOver      bool                   `protobuf:"varint,10,opt,name=game_over,json=gameOver,proto3" json:"game_over,omitempty"`   // 比赛是否结束
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundResult) Reset() {
	*x = RoundResult{}
	mi := &file_proto_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundResult) ProtoMessage() {}

func (x *RoundResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundResult.ProtoReflect.Descriptor instead.
func (*RoundResult) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{25}
}

func (x *RoundResult) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *RoundResult) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *RoundResult) GetSubRound() int32 {
	if x != nil {
		return x.SubRound
	}
	return 0
}

func (x *RoundResult) GetMyCard() int32 {
	if x != nil {
		return x.MyCard
	}
	return 0
}

func (x *RoundResult) GetOpCard() int32 {
	if x != nil {
		return x.OpCard
	}
	return 0
}

func (x *RoundResult) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *RoundResult) GetScore1() int32 {
	if x != nil {
		return x.Score1
	}
	return 0
}

func (x *RoundResult) GetScore2() int32 {
	if x != nil {
		return x.Score2
	}
	return 0
}

func (x *RoundResult) GetRoundOver() bool {
	if x != nil {
		return x.RoundOver
	}
	return false
}

func (x *RoundResult) GetGameOver() bool {
	if x != nil {
		return x.GameOver
	}
	return false
}

// 对局结束（服务端推送）
type BattleEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Winner        int64                  `protobuf:"varint,2,opt,name=winner,proto3" json:"winner,omitempty"` // 赢家UID（0=平局）
	Score1        int32                  `protobuf:"varint,3,opt,name=score1,proto3" json:"score1,omitempty"`
	Score2        int32                  `protobuf:"varint,4,opt,name=score2,proto3" json:"score2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleEnd) Reset() {
	*x = BattleEnd{}
	mi := &file_proto_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEnd) ProtoMessage() {}

func (x *BattleEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEnd.ProtoReflect.Descriptor instead.
func (*BattleEnd) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{26}
}

func (x *BattleEnd) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *BattleEnd) GetWinner() int64 {
	if x != nil {
		return x.Winner
	}
	return 0
}

func (x *BattleEnd) GetScore1() int32 {
	if x != nil {
		return x.Score1
	}
	return 0
}

func (x *BattleEnd) GetScore2() int32 {
	if x != nil {
		return x.Score2
	}
	return 0
}

type LeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Top           int32                  `protobuf:"varint,1,opt,name=top,proto3" json:"top,omitempty"` // 前N名（默认10）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardRequest) Reset() {
	*x = LeaderboardRequest{}
	mi := &file_proto_messages_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardRequest) ProtoMessage() {}

func (x *LeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardRequest.ProtoReflect.Descriptor instead.
func (*LeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{27}
}

func (x *LeaderboardRequest) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

type LeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LeaderboardItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardResponse) Reset() {
	*x = LeaderboardResponse{}
	mi := &file_proto_messages_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardResponse) ProtoMessage() {}

func (x *LeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardResponse.ProtoReflect.Descriptor instead.
func (*LeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{28}
}

func (x *LeaderboardResponse) GetItems() []*LeaderboardItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type LeaderboardItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Win           int64                  `protobuf:"varint,4,opt,name=win,proto3" json:"win,omitempty"`
	Total         int64                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	WinRate       float32                `protobuf:"fixed32,6,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardItem) Reset() {
	*x = LeaderboardItem{}
	mi := &file_proto_messages_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardItem) ProtoMessage() {}

func (x *LeaderboardItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardItem.ProtoReflect.Descriptor instead.
func (*LeaderboardItem) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{29}
}

func (x *LeaderboardItem) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardItem) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LeaderboardItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LeaderboardItem) GetWin() int64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *LeaderboardItem) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *LeaderboardItem) GetWinRate() float32 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

// 战绩查询
type BattleRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 查询最近N条
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleRecordRequest) Reset() {
	*x = BattleRecordRequest{}
	mi := &file_proto_messages_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleRecordRequest) ProtoMessage() {}

func (x *BattleRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleRecordRequest.ProtoReflect.Descriptor instead.
func (*BattleRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{30}
}

func (x *BattleRecordRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BattleRecordRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BattleRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*BattleRecordItem    `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleRecordResponse) Reset() {
	*x = BattleRecordResponse{}
	mi := &file_proto_messages_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleRecordResponse) ProtoMessage() {}

func (x *BattleRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleRecordResponse.ProtoReflect.Descriptor instead.
func (*BattleRecordResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{31}
}

func (x *BattleRecordResponse) GetRecords() []*BattleRecordItem {
	if x != nil {
		return x.Records
	}
	return nil
}

type BattleRecordItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Player1       int64                  `protobuf:"varint,2,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2       int64                  `protobuf:"varint,3,opt,name=player2,proto3" json:"player2,omitempty"`
	Winner        int64                  `protobuf:"varint,4,opt,name=winner,proto3" json:"winner,omitempty"`
	Score1        int32                  `protobuf:"varint,5,opt,name=score1,proto3" json:"score1,omitempty"`
	Score2        int32                  `protobuf:"varint,6,opt,name=score2,proto3" json:"score2,omitempty"`
	Round         int32                  `protobuf:"varint,7,opt,name=round,proto3" json:"round,omitempty"`
	Duration      int32                  `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleRecordItem) Reset() {
	*x = BattleRecordItem{}
	mi := &file_proto_messages_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleRecordItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleRecordItem) ProtoMessage() {}

func (x *BattleRecordItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleRecordItem.ProtoReflect.Descriptor instead.
func (*BattleRecordItem) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{32}
}

func (x *BattleRecordItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BattleRecordItem) GetPlayer1() int64 {
	if x != nil {
		return x.Player1
	}
	return 0
}

func (x *BattleRecordItem) GetPlayer2() int64 {
	if x != nil {
		return x.Player2
	}
	return 0
}

func (x *BattleRecordItem) GetWinner() int64 {
	if x != nil {
		return x.Winner
	}
	return 0
}

func (x *BattleRecordItem) GetScore1() int32 {
	if x != nil {
		return x.Score1
	}
	return 0
}

func (x *BattleRecordItem) GetScore2() int32 {
	if x != nil {
		return x.Score2
	}
	return 0
}

func (x *BattleRecordItem) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *BattleRecordItem) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *BattleRecordItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_proto_messages_proto protoreflect.FileDescriptor

const file_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\x14proto/messages.proto\x12\x02pb\"\v\n" +
	"\tHeartbeat\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"]\n" +
	"\rLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"#\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"b\n" +
	"\fAuthResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\"\\\n" +
	"\vChatMessage\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\"*\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\"i\n" +
	"\x10JoinRoomResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\x03R\x06roomId\x12\x16\n" +
	"\x06online\x18\x04 \x01(\x05R\x06online\"\x12\n" +
	"\x10LeaveRoomRequest\"9\n" +
	"\x11LeaveRoomResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"(\n" +
	"\fSystemNotify\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"e\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\"8\n" +
	"\x10RegisterResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x0e\n" +
	"\fMatchRequest\"5\n" +
	"\rMatchResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x14\n" +
	"\x12MatchCancelRequest\";\n" +
	"\x13MatchCancelResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x19\n" +
	"\x17BattleCreateRoomRequest\"]\n" +
	"\x18BattleCreateRoomResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1b\n" +
	"\troom_code\x18\x03 \x01(\tR\broomCode\"4\n" +
	"\x15BattleJoinRoomRequest\x12\x1b\n" +
	"\troom_code\x18\x01 \x01(\tR\broomCode\">\n" +
	"\x16BattleJoinRoomResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"x\n" +
	"\vBattleStart\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\x12\x1a\n" +
	"\bopponent\x18\x02 \x01(\x03R\bopponent\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05round\x18\x04 \x01(\x05R\x05round\"\xf2\x01\n" +
	"\vBattleState\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\x12\x1a\n" +
	"\bopponent\x18\x02 \x01(\x03R\bopponent\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05round\x18\x04 \x01(\x05R\x05round\x12\x1b\n" +
	"\tsub_round\x18\x05 \x01(\x05R\bsubRound\x12\x16\n" +
	"\x06score1\x18\x06 \x01(\x05R\x06score1\x12\x16\n" +
	"\x06score2\x18\a \x01(\x05R\x06score2\x12\x12\n" +
	"\x04hand\x18\b \x03(\x05R\x04hand\x12\x17\n" +
	"\amy_turn\x18\t \x01(\bR\x06myTurn\"K\n" +
	"\x0fPlayCardRequest\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\x12\x1b\n" +
	"\tcard_type\x18\x02 \x01(\x05R\bcardType\"8\n" +
	"\x10PlayCardResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x93\x02\n" +
	"\vRoundResult\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x05R\x05round\x12\x1b\n" +
	"\tsub_round\x18\x03 \x01(\x05R\bsubRound\x12\x17\n" +
	"\amy_card\x18\x04 \x01(\x05R\x06myCard\x12\x17\n" +
	"\aop_card\x18\x05 \x01(\x05R\x06opCard\x12\x16\n" +
	"\x06result\x18\x06 \x01(\x05R\x06result\x12\x16\n" +
	"\x06score1\x18\a \x01(\x05R\x06score1\x12\x16\n" +
	"\x06score2\x18\b \x01(\x05R\x06score2\x12\x1d\n" +
	"\n" +
	"round_over\x18\t \x01(\bR\troundOver\x12\x1b\n" +
	"\tgame_over\x18\n" +
	" \x01(\bR\bgameOver\"p\n" +
	"\tBattleEnd\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\x12\x16\n" +
	"\x06winner\x18\x02 \x01(\x03R\x06winner\x12\x16\n" +
	"\x06score1\x18\x03 \x01(\x05R\x06score1\x12\x16\n" +
	"\x06score2\x18\x04 \x01(\x05R\x06score2\"&\n" +
	"\x12LeaderboardRequest\x12\x10\n" +
	"\x03top\x18\x01 \x01(\x05R\x03top\"@\n" +
	"\x13LeaderboardResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.pb.LeaderboardItemR\x05items\"\x96\x01\n" +
	"\x0fLeaderboardItem\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x10\n" +
	"\x03win\x18\x04 \x01(\x03R\x03win\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x03R\x05total\x12\x19\n" +
	"\bwin_rate\x18\x06 \x01(\x02R\awinRate\"=\n" +
	"\x13BattleRecordRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"F\n" +
	"\x14BattleRecordResponse\x12.\n" +
	"\arecords\x18\x01 \x03(\v2\x14.pb.BattleRecordItemR\arecords\"\xef\x01\n" +
	"\x10BattleRecordItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aplayer1\x18\x02 \x01(\x03R\aplayer1\x12\x18\n" +
	"\aplayer2\x18\x03 \x01(\x03R\aplayer2\x12\x16\n" +
	"\x06winner\x18\x04 \x01(\x03R\x06winner\x12\x16\n" +
	"\x06score1\x18\x05 \x01(\x05R\x06score1\x12\x16\n" +
	"\x06score2\x18\x06 \x01(\x05R\x06score2\x12\x14\n" +
	"\x05round\x18\a \x01(\x05R\x05round\x12\x1a\n" +
	"\bduration\x18\b \x01(\x05R\bduration\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAtB\x0fZ\r./internal/pbb\x06proto3"

var (
	file_proto_messages_proto_rawDescOnce sync.Once
	file_proto_messages_proto_rawDescData []byte
)

func file_proto_messages_proto_rawDescGZIP() []byte {
	file_proto_messages_proto_rawDescOnce.Do(func() {
		file_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)))
	})
	return file_proto_messages_proto_rawDescData
}

var file_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_messages_proto_goTypes = []any{
	(*Heartbeat)(nil),                // 0: pb.Heartbeat
	(*LoginRequest)(nil),             // 1: pb.LoginRequest
	(*LoginResponse)(nil),            // 2: pb.LoginResponse
	(*AuthRequest)(nil),              // 3: pb.AuthRequest
	(*AuthResponse)(nil),             // 4: pb.AuthResponse
	(*ChatMessage)(nil),              // 5: pb.ChatMessage
	(*JoinRoomRequest)(nil),          // 6: pb.JoinRoomRequest
	(*JoinRoomResponse)(nil),         // 7: pb.JoinRoomResponse
	(*LeaveRoomRequest)(nil),         // 8: pb.LeaveRoomRequest
	(*LeaveRoomResponse)(nil),        // 9: pb.LeaveRoomResponse
	(*SystemNotify)(nil),             // 10: pb.SystemNotify
	(*RegisterRequest)(nil),          // 11: pb.RegisterRequest
	(*RegisterResponse)(nil),         // 12: pb.RegisterResponse
	(*MatchRequest)(nil),             // 13: pb.MatchRequest
	(*MatchResponse)(nil),            // 14: pb.MatchResponse
	(*MatchCancelRequest)(nil),       // 15: pb.MatchCancelRequest
	(*MatchCancelResponse)(nil),      // 16: pb.MatchCancelResponse
	(*BattleCreateRoomRequest)(nil),  // 17: pb.BattleCreateRoomRequest
	(*BattleCreateRoomResponse)(nil), // 18: pb.BattleCreateRoomResponse
	(*BattleJoinRoomRequest)(nil),    // 19: pb.BattleJoinRoomRequest
	(*BattleJoinRoomResponse)(nil),   // 20: pb.BattleJoinRoomResponse
	(*BattleStart)(nil),              // 21: pb.BattleStart
	(*BattleState)(nil),              // 22: pb.BattleState
	(*PlayCardRequest)(nil),          // 23: pb.PlayCardRequest
	(*PlayCardResponse)(nil),         // 24: pb.PlayCardResponse
	(*RoundResult)(nil),              // 25: pb.RoundResult
	(*BattleEnd)(nil),                // 26: pb.BattleEnd
	(*LeaderboardRequest)(nil),       // 27: pb.LeaderboardRequest
	(*LeaderboardResponse)(nil),      // 28: pb.LeaderboardResponse
	(*LeaderboardItem)(nil),          // 29: pb.LeaderboardItem
	(*BattleRecordRequest)(nil),      // 30: pb.BattleRecordRequest
	(*BattleRecordResponse)(nil),     // 31: pb.BattleRecordResponse
	(*BattleRecordItem)(nil),         // 32: pb.BattleRecordItem
}
var file_proto_messages_proto_depIdxs = []int32{
	29, // 0: pb.LeaderboardResponse.items:type_name -> pb.LeaderboardItem
	32, // 1: pb.BattleRecordResponse.records:type_name -> pb.BattleRecordItem
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_messages_proto_init() }
func file_proto_messages_proto_init() {
	if File_proto_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messages_proto_goTypes,
		DependencyIndexes: file_proto_messages_proto_depIdxs,
		MessageInfos:      file_proto_messages_proto_msgTypes,
	}.Build()
	File_proto_messages_proto = out.File
	file_proto_messages_proto_goTypes = nil
	file_proto_messages_proto_depIdxs = nil
}
