syntax = "proto3";
package pb;
option go_package = "./internal/pb";

//心跳体
message Heartbeat{}

//登录请求
message LoginRequest{
    string username = 1;
    string password = 2;
}

//登录响应
message LoginResponse{
    int32 code = 1; // 0=成功, 其它=失败
    string msg = 2;
    int64 uid = 3; // 成功时返回玩家ID
    string token = 4 ; // 成功时返回JWT TOKEN
}

message AuthRequest {
    string token = 1;
}

message AuthResponse {
    int32 code = 1; //0=成功，1=token无效, 2=token过期
    string msg = 2;
    int64 uid = 3;
    string nickname = 4;
}

// 聊天消息
message ChatMessage {
  int64  room_id  = 1;
  string content  = 2;
  string nickname = 3;
}

message JoinRoomRequest {
    int64 room_id = 1;  //目标房间ID
}

message JoinRoomResponse {
    int32 code  = 1;    //0=成功
    string msg  = 2;
    int64 room_id   = 3;    //实际加入的房间ID
    int32 online    = 4;    //房间内当前人数
}


message LeaveRoomRequest {

}

message LeaveRoomResponse {
    int32 code = 1;
    string msg = 2;
}

message SystemNotify {
    string content = 1; //通知内容
}

message RegisterRequest {
    string username = 1;
    string password = 2;
    string nickname = 3;
}

message RegisterResponse {
    int32 code = 1;
    string msg = 2;
}