port: ":8080"
ws_port: ":8081"

heartbeat:
  timeout: 30   #超过30秒没收到心跳自动断开

jwt:
  secret: "secret"
  expire_hours: 24 #token过期时间

database:
  host: "localhost"
  port: 3306
  user: "jcf"
  password: "jcf310978155"
  dbname: "game_server"
  max_open_conns: 100       #最大连接数
  max_idle_conns: 20        #最大空闲连接数
  conn_max_lifetime: 3600   #连接最大存活时间


redis:
  addr: "localhost:32768"
  password: ""
  db: 0
  pool_size: 100
  min_idle_conns: 10
  pool_timeout: 5
