port: ":8080"

heartbeat:
  timeout: 30   #超过30秒没收到心跳自动断开

database:
  host: "localhost"
  port: 3306
  user: "jcf"
  password: "jcf310978155"
  dbname: "game_server"
  max_open_conns: 10
  max_idle_conns: 5